---
- hosts: dev
  vars:
    - mas_installed_apps:
      - { id: 1035236694, name: "Commander One (1.7.3)" }
      - { id: 409183694, name: "Keynote (7.3)" }
      - { id: 408981434, name: "iMovie (10.1.7)" }
      - { id: 715768417, name: "Microsoft Remote Desktop (8.0.27325)" }
      - { id: 406056744, name: "Evernote (6.12.3)" }
      - { id: 803453959, name: "Slack (2.8.1)" }
      - { id: 1004520921, name: "Chat for Facebook (1.0)" }
      - { id: 1013897218, name: "App Cleaner (4.5)" }
    - applications:
#      - google-drive-file-stream
#      - docker
#      - google-chrome
      - java
      - nextcloud
      - p4merge
      - hammerspoon
      - sequel-pro
      - sourcetree
      - visual-studio-code
      - appcleaner
      - jetbrains-toolbox
  roles:
    - role: geerlingguy.homebrew
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']
  tasks:
    - name: install gnu tools
      homebrew: name={{item}}
      install_options: '--with-default-names'
      with_items:
      - coreutils
      - binutils
      - diffutils
      - findutils
      - gawk
      - gnu-sed
      - gnu-tar
      - gnu-which
      - grep

    - name: installing cask packages by homebrew
      homebrew_cask:
        name: "{{item}}"
        install_options: 'appdir=/Applications'
        state: present
      with_items: "{{applications}}"

    - name: installing packages by homebrew
#      homebrew: update_homebrew=yes name={{item}}
      homebrew: name={{item}}
      with_items:
        - caskroom/versions/java8
        - ack
        - gradle-completion
        - sonar-scanner
        - httpie
        - git
        - docker-completion
        - vim
        - thefuck
        - imagemagick
        - xz
        - nmap
        - vault
        - git-extras
        - mr
        - vcsh
        - wget
        - tig
        - python
        - tmux
        - ncdu
        - zsh
        - watch
        - mas
      tags:
        - homebrew
#
#    - name: Check for installed apps(casks)
#      shell: brew cask list | grep {{ item }}
#      register: installed_applications
#      with_items: "{{ applications }}"
#      ignore_errors: true
#
#    - name: Install apps with brew-cask
#      shell: brew cask install {{ item }}
#      with_items: "{{ applications }}"
#      when: item not in installed_applications.results|map(attribute='stdout')
